### ISSUE TITLE
Can't find the 'closeButton'

### ISSUE THREAD

**Issue by wangs664518990** [HaxeExtension/extension-webview#1]
Hello,I use the library on IOS platform,with popu mode.But I can't find on buton to close it.

**Comment by fbricker** [comment]
Hi, can you post your source code here to see how are you using it.
Please make sure you're passing true to the second argument to the open function (this makes the library to use the floating mode and place a close button).

Example: WebView.open('http://www.puralax.com/help',true);

Thanks!

**Comment by wangs664518990** [comment]
I used it like this, 'WebView.open("http://www.baidu.com/",true);' . Click on the upper right corner of it, can close it.But can not see the close button.

**Comment by wangs664518990** [comment]
package com.xiaoao.ddz;

import extension.webview.WebView;
import flash.display.Sprite;
import flash.events.Event;
import flash.Lib;

/**
- ...
- @author Wangmingli
  */

class Main extends Sprite 
{
    var inited:Bool;

```
/* ENTRY POINT */

function resize(e) 
{
    if (!inited) init();
    // else (resize or orientation change)
}

function init() 
{
    if (inited) return;
    inited = true;

    // (your code here)

    // Stage:
    // stage.stageWidth x stage.stageHeight @ stage.dpiScale
    WebView.open("http://www.baidu.com/",true);
    // Assets:
    // nme.Assets.getBitmapData("img/assetname.jpg");
}

/* SETUP */

public function new() 
{
    super();    
    addEventListener(Event.ADDED_TO_STAGE, added);
}

function added(e) 
{
    removeEventListener(Event.ADDED_TO_STAGE, added);
    stage.addEventListener(Event.RESIZE, resize);
    #if ios
    haxe.Timer.delay(init, 100); // iOS 6
    #else
    init();
    #end
}

public static function main() 
{
    // static entry point
    Lib.current.stage.align = flash.display.StageAlign.TOP_LEFT;
    Lib.current.stage.scaleMode = flash.display.StageScaleMode.NO_SCALE;
    Lib.current.addChild(new Main());
}
```

}

**Comment by fbricker** [comment]
I'm testing your sample and it's working fine for me (I see the close button on the upper left corner).

![ios simulator screen shot 23 1 2015 9 27 40](https://cloud.githubusercontent.com/assets/1865352/5874582/2fc0bae4-a2e2-11e4-9575-516997837b5f.png)

Do you have the last version of the extension installed?

**Comment by wangs664518990** [comment]
I used the old APIs.I will have a try about the last version of the extension.
