### ISSUE TITLE
OnURLChanging event

### ISSUE THREAD

**Issue by StephenKDS** [HaxeExtension/extension-webview#2]
This doesn't appear to fire on Android - the Open/Close events do - something wierd is going on.

I set the URL to https://www.google.co.nz - which loads fine in the window. Any links clicked inside, (which navigate around), don't appear to fire that event.

Any ideas?

**Comment by StephenKDS** [comment]
Testing on 5.0.1 (Lollipop) and 4.4.2 (Kit Kat), with no difference.

**Comment by fbricker** [comment]
Hi, most probably you are using the version 1.1.0 (from haxelib).
That version did not had changing event implemented for android.
I've just uploaded version 1.2.0 to haxelib with support for Android Events :)

Please test it and let me know if everything works fine :+1: 

Thanks!

**Comment by StephenKDS** [comment]
brilliant. works on android now. Thank you!
