### ISSUE TITLE
Haxelib

### ISSUE THREAD

**Issue by Netforza** [HaxeExtension/extension-webview#5]
haxelib install extension-webview        returns:
No such Project : extention-webview

While openfl-webview gives 
Error: OPENFL-WEBVIEW IS DEPRECATED! Now you should use 'extension-webview'
when I try to build the project.

**Comment by fbricker** [comment]
Hi, I'm testing here and seems to be working fine.
Just in case, please check that you might be writing the extension name wrong, as your message says:

No such Project : **extention-webview**
instead of
No such Project : **extension-webview**

**Comment by Netforza** [comment]
Yes indeed,  haxelib install extension-webview works.
I should have copy pasted it. 
Sorry for bothering you.
