### ISSUE TITLE
Local Storage not working in the webview on Android

### ISSUE THREAD

**Issue by Netforza** [HaxeExtension/extension-webview#6]
The Android webview does not support local storage.

I managed to enable it locally by adding:

``` java
webSettings.setDomStorageEnabled(true);
```

to WebViewActivity.java

**Comment by fbricker** [comment]
Hi, that's great... can you do a pull request to add that feature to the extension?

**Comment by Netforza** [comment]
Sorry Federico.
I am not good with github. 
I did the changes on the extension installed via haxelib.

It would be easier if you implement it: 
Just open 
`WebViewActivity.java`
find 
`webSettings.setJavaScriptEnabled(true);`
and add below 
`webSettings.setDomStorageEnabled(true);`

**Comment by fbricker** [comment]
Done, I've added this and released a new version on haxelib.
Thanks for your contribution.

PS: You should try doing some pull requests on github (it's not that complicated, and once you find out how to make them, you can begin to contribute a lot more to the open source community) 👍 

In case you're interested on this, you have basically three ways:
**1) Create a fork and edit that on your own repo:**
Click on the fork option on the repository and then edit and change the project on your own repository. Then, on the github's page of your fork (github.com/YOUUSER/THEPROJECT) you will see a "send pull request" button. That will create a pull request with your changes for the main project.  
After that you can just delete your fork, or keep it if you wish.

**2) Edit the files directly on github:**
If you want to change/edit just one file, you can click the edit button (a pencil) that appears at the top-right corner when you open a file. Then, when you edit the file and click save, you'll have the option to create a pull request, and that's it.

**3) Ask to be added a contributor on the repository:**
In case you're willing to provide support and make big contributions on a project, you can just request to be added as contributor so you can commit directly into the repository without creating pull requests.
